app_name = "branded_lms"
app_title = "Branded LMS"
app_publisher = "Your Company"
app_description = "LMS integration for Dation & Educators"
app_icon = "octicon octicon-file-directory"
app_color = "grey"
app_email = "info@yourcompany.com"
app_license = "MIT"
