[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "branded_lms"
version = "0.0.1" 
description = "LMS App"
authors = [
    { name = "Your Name", email = "you@example.com" },
]

